apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: airflow
spec:
  selector:
    app: postgres
  type: ClusterIP
  ports:
  - name: postgres
    protocol: TCP
    port: 5432
    targetPort: 5432


---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:11.4
          env:
          - name: POSTGRES_USER 
            value: "airflow"
          - name: POSTGRES_PASSWORD 
            value: "password"
          - name: POSTGRES_DB
            value: "f1"  
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
          ports: 
            - containerPort: 5432
              name: access
              protocol: TCP
          volumeMounts:
            - name: postgres-mount
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-mount
          persistentVolumeClaim:
            claimName: postgres-volume-claim
      

--- 

apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/postgres
  storageClassName: standard

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim
  namespace: airflow
  labels:
    app: postgres
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi