[tool.poetry]
name = "05-helm"
version = "0.1.0"
description = ""
authors = ["Oliver Giles <ogiles@email.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
cryptography = "^41.0.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
